import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import {Toaster} from "@/components/ui/toaster";
import Header from "@/components/header";
import Footer from "@/components/footer";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AlgoViz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <NextTopLoader color={'hsl(141.9 69.2% 58%)'}/>
      <Header/>
      <main className={'w-full'}>{children}</main>
      <Footer/>
      <Toaster/>
      </body>
    </html>
  );
}
